const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async()=>{
 const browser = await chromium.launch({headless:true, executablePath:process.env.CHROME_PATH || '/usr/bin/google-chrome',args:['--no-sandbox']});
 try {
  const page = await browser.newPage({viewport:{width:390,height:844}});
  await page.addInitScript(() => localStorage.setItem('memora-demo-language','zh'));
  const errors=[]; page.on('pageerror',e=>errors.push(e.message));
  let response = {entities:[{type:'client',name:'Intake Demo',city:'Markham',evidence:'新客户 Intake Demo'}],warnings:[]};
  await page.route('**/functions/v1/sculpy-ai*',route=>route.fulfill({json:response}));
  await page.goto('http://localhost:4173/?demo=1#bookings/b0');
  await page.locator('#context-memories [data-memory-open]').click();
  await page.locator('#memory-target').selectOption('');
  await page.locator('#memory-text').fill('  新客户 Intake Demo，在 Markham。  ');
  const identify=()=>page.locator('[data-memory-identify]').click();
  await identify();
  await page.locator('[data-entity-review]').waitFor();
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('sculp-memory-demo-v1')||'{}').demoClients?.length||0),0);
  await page.locator('[data-entity-review]').click();
  assert.equal(await page.locator('#memory-new-name').inputValue(),'Intake Demo');
  await page.locator('#memory-new-city').fill('Toronto');
  await page.locator('[data-memory-create-submit]').click();
  await page.waitForFunction(()=>document.querySelector('#memory-target option:checked')?.textContent.includes('Intake Demo'));
  let stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('sculp-memory-demo-v1')));
  assert.equal(stored.demoClients.length,1); assert.equal(stored.demoClients[0].city,'Toronto');
  assert.equal(stored.memories[0].rawText,'  新客户 Intake Demo，在 Markham。  ');
  assert(stored.memories[0].recordedAt);
  const clientId=stored.demoClients[0].id;
  response={entities:[{type:'booking',name:'Intake Demo',date:'2026-11-20',service:'Wedding',artist:'unknown',venue:'unknown',evidence:'2026年11月20日婚礼'}],warnings:[]};
  await page.locator('#memory-text').fill('Intake Demo，2026年11月20日婚礼，负责人和场地待确认。');
  await identify(); await page.locator('[data-entity-review]').click();
  assert.equal(await page.locator('#memory-new-client').inputValue(),clientId);
  assert.equal(await page.locator('#memory-new-artist').inputValue(),'');
  assert.equal(await page.locator('#memory-new-venue').inputValue(),'');
  await page.locator('[data-memory-create-submit]').click();
  await page.getByText(/请选择负责人和场地/).waitFor();
  await page.locator('#memory-new-artist').selectOption('miranda');
  await page.locator('#memory-new-venue').selectOption('graydon');
  assert(await page.locator('.memory-dialog').evaluate(el=>el.scrollWidth<=innerWidth));
  await page.screenshot({path:'qa-screens/intake-mobile.png'});
  await page.locator('[data-memory-create-submit]').click();
  await page.waitForFunction(()=>document.querySelector('#memory-target option:checked')?.textContent.includes('2026-11-20'));
  stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('sculp-memory-demo-v1')));
  assert.equal(stored.demoBookings.length,1); assert.equal(stored.memories.length,2);
  await page.getByRole('button',{name:'关闭记录面板'}).click();
  await page.reload(); await page.goto('http://localhost:4173/?demo=1#clients/'+clientId);
  await page.locator('#context-memories details').first().evaluate(el=>el.open=true);
  assert.match(await page.locator('#context-memories').innerText(),/新客户 Intake Demo/);
  await page.locator('#context-memories [data-memory-open]').click();
  await page.locator('#memory-text').fill('新的输入'); await identify(); await page.locator('[data-entity-review]').waitFor();
  await page.locator('#memory-text').fill('已修改，不要创建');
  assert.equal(await page.locator('[data-entity-review]').count(),0);
  await page.getByRole('button',{name:'关闭记录面板'}).click();
  await page.selectOption('#role','artist');
  await page.goto('http://localhost:4173/?demo=1#bookings/b0');
  await page.locator('#context-memories [data-memory-open]').click();
  assert.equal(await page.locator('[data-memory-identify]').count(),0);
  assert.deepEqual(errors,[]);
  console.log('Intake: no pre-confirmation write, editable cards, missing-field blocks, source fidelity, reload, invalidation, employee isolation and mobile passed');
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
