import {createChatPanel} from './components/chat/panel.js?v=single-chat-2';
import {demoChatAdapter} from './services/chat.js?v=single-chat-2';
import {searchCatalog} from './domain/sculpy.js';
import {clientPreferences} from './domain/memory.js';
import {createMemoryPanel} from './components/memory/panel.js?v=single-chat-2';
import {createDemoMemoryRepository,createCloudMemoryRepository} from './services/memory.js';
import {artists,clients,venues,partners,bookings,notes,media,portfolioMedia} from './data/demo.js?v=20261004-mira';
import {loadState,saveState,resetState} from './services/storage.js';
import {config} from './config.js';
import {createSculpyPage} from './pages/sculpy/index.js';
import {createInsights} from './pages/insights/index.js';
import {wantsRevenueChart,createRevenueChart} from './pages/insights/chart.js';
import {canViewBusiness,canViewTechnical,visibleBookings} from './domain/permissions.js';
const hydrateDemoEntities=()=>{for(const c of state.demoClients||[])if(!clients.some(x=>x.id===c.id))clients.push(c);for(const b of state.demoBookings||[])if(!bookings.some(x=>x.id===b.id))bookings.push(b)};
let state=loadState(),role='admin',adminPersona='jz',artistId='michelle',view='list',month='2026-10',tour=0;
let filters={q:'',artist:'',service:'',status:'',date:'',venue:'',category:''};
hydrateDemoEntities();
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const get=(arr,id)=>arr.find(x=>x.id===id),client=id=>get(clients,id),artist=id=>get(artists,id),venue=id=>get(venues,id),partner=id=>get(partners,id);
const serviceName={Wedding:'婚礼造型',Trial:'婚礼试妆',Event:'活动造型',Photoshoot:'拍摄造型',Commercial:'商业造型',Education:'教学'};
const statusName={Completed:'已完成',Confirmed:'已确认',Inquiry:'咨询中',Cancelled:'已取消'};
const titles={bookings:['Bookings','场次记录'],clients:['Clients','客户档案'],artists:['Artists','化妆师'],venues:['Venues','场地'],partners:['Partners','合作方'],media:['Media Library','作品图库'],insights:['Studio Insights','工作室概览'],sculpy:['Hello, Sculpy','Sculpy 助手'],settings:['Settings','设置']};
const iconPaths=['<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4M17 3v4M3 10h18"/>','<circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>','<circle cx="9" cy="8" r="3"/><path d="M2 20v-2a7 7 0 0 1 14 0v2M16 5a3 3 0 0 1 0 6M18 14a5 5 0 0 1 4 5"/>','<path d="M12 22s8-8 8-13a8 8 0 0 0-16 0c0 5 8 13 8 13Z"/><circle cx="12" cy="9" r="2.5"/>','<path d="m8 8 5-4 7 4 2 5-8 8-5-3-7-5 3-5h3Z"/><path d="m8 8 5 5 4-4M7 15l4 4"/>','<rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8" cy="8" r="2"/><path d="m3 18 6-6 4 4 4-5 4 5"/>','<path d="M4 20V10M12 20V4M20 20v-7"/>','<path d="m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3Z"/>','<circle cx="12" cy="12" r="3"/><path d="m9 3 6 0 1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1 1-3Z"/>'];
const navItems=Object.keys(titles);
const getContext=()=>({state,role,adminPersona,artistId});
const isGlobal=()=>canViewBusiness(getContext());
const isTechnical=()=>canViewTechnical(getContext());
const bookingArtists=artists.filter(a=>a.bookingEligible!==false);
const available=()=>visibleBookings(bookings,getContext());
const visibleMedia=()=>media.filter(m=>available().some(b=>b.id===m.bookingId));
const countFor=(type,id)=>available().filter(b=>type==='clients'?b.clientId===id:type==='artists'?b.artistIds.includes(id):type==='venues'?b.venueId===id:b.partnerIds.includes(id));
const money=n=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD',maximumFractionDigits:0}).format(n);
const date=d=>new Date(d+'T12:00:00').toLocaleDateString('en-CA',{month:'short',day:'numeric',year:'numeric'});
const link=(type,id,name)=>`<a class="link" href="#${type}/${esc(id)}">${esc(name)}</a>`;
const pill=s=>`<span class="pill ${s.toLowerCase()}">${statusName[s]}</span>`;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('visible'),3000)}
function persist(){if(!saveState(state))toast('浏览器无法保存，当前改动将在关闭后消失。')}
function stats(items){return `<div class="stats">${items.map(([v,l])=>`<div class="stat"><div class="value">${esc(v)}</div><div class="label">${esc(l)}</div></div>`).join('')}</div>`}
function head(key,description,buttons=''){return `<div class="page-head"><div><div class="eyebrow">SCULP / ${titles[key][1]}</div><h1>${titles[key][0]}</h1><p>${description}</p></div><div class="head-buttons">${buttons}</div></div>`}
function selectOptions(arr,label,value=''){return `<option value="">${label}</option>${arr.map(a=>`<option value="${esc(a.id||a)}" ${(a.id||a)===value?'selected':''}>${esc(a.name||serviceName[a]||statusName[a]||a)}</option>`).join('')}`}
function filtered(){return available().filter(b=>{const q=filters.q.toLowerCase();return (!q||[client(b.clientId).name,...b.artistIds.map(x=>artist(x).name),venue(b.venueId).name,...b.partnerIds.map(x=>partner(x).name),serviceName[b.service],b.date].join(' ').toLowerCase().includes(q))&&(!filters.artist||b.artistIds.includes(filters.artist))&&(!filters.service||b.service===filters.service)&&(!filters.status||b.status===filters.status)&&(!filters.date||b.date===filters.date)&&(!filters.venue||b.venueId===filters.venue)}).sort((a,b)=>b.date.localeCompare(a.date))}
function bookingTable(list){if(!list.length)return '<div class="empty">没有符合条件的场次。试试调整筛选。</div>';return `<div class="table-wrap"><table><thead><tr><th>日期 / 时间</th><th>客户 / 服务</th><th>负责化妆师</th><th>场地</th><th>合作方</th>${isGlobal()?'<th>金额 · CAD</th>':''}<th>状态</th></tr></thead><tbody>${list.map(b=>`<tr><td>${link('bookings',b.id,date(b.date))}<span class="meta">${b.startTime} – ${b.endTime}</span></td><td>${isGlobal()?link('clients',b.clientId,client(b.clientId).name):esc(client(b.clientId).name)}<span class="meta">${link('bookings',b.id,serviceName[b.service])}</span></td><td>${b.artistIds.map(id=>`<div>${isGlobal()||id===artistId?link('artists',id,artist(id).name):esc(artist(id).name)}</div>`).join('')}</td><td>${link('venues',b.venueId,venue(b.venueId).name)}</td><td>${b.partnerIds.slice(0,2).map(id=>`<div>${link('partners',id,partner(id).name)}</div>`).join('')||'—'}</td>${isGlobal()?`<td>${money(b.price)}</td>`:''}<td>${pill(b.status)}</td></tr>`).join('')}</tbody></table></div>`}
function calendar(list){const [year,mm]=month.split('-').map(Number),first=new Date(year,mm-1,1).getDay(),days=new Date(year,mm,0).getDate();return `<div class="calendar-head"><button data-month="-1" aria-label="上个月">‹</button><h2 style="margin:0">${new Date(year,mm-1,1).toLocaleDateString('en-CA',{month:'long',year:'numeric'})}</h2><button data-month="1" aria-label="下个月">›</button></div><div class="calendar-week">${['SUN','MON','TUE','WED','THU','FRI','SAT'].map(x=>`<span>${x}</span>`).join('')}</div><div class="calendar">${Array.from({length:Math.ceil((first+days)/7)*7},(_,i)=>{const day=i-first+1,d=month+'-'+String(day).padStart(2,'0');return `<div class="calendar-cell ${day<1||day>days?'dim':''} ${d==='2026-10-03'?'today-date':''}">${day<1||day>days?'':`<span>${day}</span>${list.filter(b=>b.date===d).map(b=>`<a class="calendar-event" href="#bookings/${b.id}">${b.startTime} ${esc(client(b.clientId).name)}<br>${serviceName[b.service]}</a>`).join('')}`}</div>`}).join('')}</div>`}
function bookingsPage(){const all=available(),today=all.filter(b=>b.date==='2026-10-03'),featured=today[0]||all[0];return head('bookings',role==='admin'?'从一场工作开始，找回所有相关的人与作品。':`${artist(artistId).name}，这里记录着你参与过的每一场。`,`<button data-action="tour">发布会演示</button><a class="primary" style="padding:10px 16px;border-radius:6px;font-size:14px" href="#sculpy">记录今天的工作</a>`)+stats([[all.length,'已收录场次'],[all.filter(b=>b.status==='Confirmed').length,'待服务场次'],[new Set(all.map(b=>b.clientId)).size,'服务客户'],[visibleMedia().length,'归档照片']])+`<div class="today"><div class="feature"><div class="date-block"><div class="eyebrow">OCT 2026</div><div class="day">03</div><div class="eyebrow">SATURDAY</div></div><div><div class="eyebrow" style="margin-bottom:7px">${today.length?'今天的安排':'最近的工作'}</div><h3>${esc(client(featured.clientId).name)}</h3><p>${serviceName[featured.service]} · ${esc(venue(featured.venueId).name)}<br>${featured.startTime} – ${featured.endTime} / ${featured.artistIds.map(x=>artist(x).name).join(' + ')}</p><a href="#bookings/${featured.id}">查看场次</a></div></div><div class="memory-card"><div class="memory-mark">S.</div><div><h3>SCULP 开始有记忆了。</h3><p>客户的偏好、团队的作品、一起合作过的人。<br>把已经做过的工作，真正留下来。</p></div></div></div><div class="section-head"><h2>全部场次</h2><div class="view-toggle"><button data-view="list" class="${view==='list'?'active':''}">列表</button><button data-view="calendar" class="${view==='calendar'?'active':''}">日历</button></div></div><div class="toolbar"><label class="sr-only" for="search">搜索场次、客户、化妆师、场地、合作方</label><input id="search" type="search" data-filter="q" value="${esc(filters.q)}" placeholder="搜索客户、化妆师、场地或合作方"><select aria-label="化妆师筛选" data-filter="artist">${selectOptions(role==='admin'?artists:[artist(artistId)],'全部化妆师',filters.artist)}</select><select aria-label="服务筛选" data-filter="service">${selectOptions(Object.keys(serviceName),'全部服务',filters.service)}</select><select aria-label="状态筛选" data-filter="status">${selectOptions(Object.keys(statusName),'全部状态',filters.status)}</select><select aria-label="场地筛选" data-filter="venue">${selectOptions(venues,'全部场地',filters.venue)}</select><input aria-label="日期筛选" type="date" data-filter="date" value="${filters.date}"><button data-action="clear">清除筛选</button></div><div id="booking-results">${view==='list'?bookingTable(filtered()):calendar(filtered())}<div class="results">${filtered().length} 场 · 所有记录均为示例</div></div>`}
function mediaGrid(list,reorder=false,official=false){if(!list.length)return '<div class="empty">这里还没有照片。在场次图库中点 ♡，加入个人精选。</div>';return `<div class="gallery ${reorder?'':'large'}">${list.map(m=>{const selected=state.selections.some(x=>x.mediaId===m.id&&x.artistId===artistId);return `<div class="media-card"><button class="photo-button" data-photo="${m.id}" data-official="${official?'true':''}" aria-label="查看 ${esc(m.category)} 作品"><img src="${m.fileUrl}" alt="${esc(m.category)} · SCULP 作品" loading="lazy"></button><div class="photo-meta"><span>${official?esc(artist(m.artistIds[0]).name):esc(m.category)}<br>${official?'官网精选':m.createdAt}</span>${official?'':`<div class="media-controls">${reorder?`<button data-order="${m.id}" data-direction="-1" aria-label="向前移动照片">‹</button><button data-order="${m.id}" data-direction="1" aria-label="向后移动照片">›</button>`:''}<button class="heart ${selected?'selected':''}" data-select="${m.id}" aria-label="${selected?'从精选移除':'加入个人精选'}" aria-pressed="${selected}">${selected?'♥':'♡'}</button></div>`}</div></div>`}).join('')}</div>`}
function noteCard(n){return `<div class="summary">${esc(n.aiSummary||'尚未整理摘要。原话已保留。')}</div>${n.summarySource==='prepared_demo'?'<div class="fake-note">AI 摘要 · 预先整理的演示内容</div>':'<div class="fake-note">摘要 · 人工确认</div>'}<div class="tag-list">${(n.structuredData?.preferences||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div>${isGlobal()?(n.structuredData?.opportunities||[]).map(t=>`<p class="opportunity">可跟进：${esc(t)}</p>`).join(''):''}<div class="note-meta">${esc(artist(n.createdBy)?.name||'Admin')} · ${date(n.createdAt.slice(0,10))} · ${n.source==='sculpy_text'?'Sculpy 文字记录':'手动记录'}</div><details><summary>查看完整原话</summary><div class="raw">${esc(n.rawText)}</div></details>`}
function bookingDetail(id){const b=available().find(x=>x.id===id);if(!b)return restricted();const ns=[...notes,...state.notes].filter(n=>n.entityId===id),photos=media.filter(m=>m.bookingId===id);return `<a class="back" href="#bookings">‹ 返回场次记录</a><div class="detail-head"><div><div class="eyebrow">BOOKING / ${b.id.toUpperCase()}</div><h1>${role==='admin'?link('clients',b.clientId,client(b.clientId).name):esc(client(b.clientId).name)}</h1><div class="service">${date(b.date)} · ${b.startTime} – ${b.endTime} · ${serviceName[b.service]}</div></div><div>${role==='admin'?`<div class="big-money">${money(b.price)} <small>CAD</small></div>`:''}${pill(b.status)}</div></div><div class="two-col"><div class="stack"><section class="panel"><h2>这一场，由这些人一起完成</h2><div class="entity-row"><span class="label">负责化妆师</span><div class="links">${b.artistIds.map((x,i)=>`<div>${role==='admin'||x===artistId?link('artists',x,artist(x).name):esc(artist(x).name)}<div class="subline">${i?'协作造型':'主造型师'}</div></div>`).join('')}</div></div><div class="entity-row"><span class="label">场地</span><div style="text-align:right">${link('venues',b.venueId,venue(b.venueId).name)}<div class="subline">${esc(venue(b.venueId).address)}</div></div></div>${b.partnerIds.map(x=>`<div class="entity-row"><span class="label">${partner(x).type}</span>${link('partners',x,partner(x).name)}</div>`).join('')}</section><section class="panel"><div class="section-head"><h2>工作记录</h2><button class="small" data-memory-open>＋ 告诉 Sculpy</button></div>${ns.map(n=>`<div>${noteCard(n)}</div>`).join('<div class="divider"></div>')}</section><section class="panel"><div class="section-head"><h2>这场的照片 <span>/${photos.length}</span></h2><span>示例作品</span></div><div class="toolbar"><select aria-label="照片分类" data-gallery="${id}">${selectOptions([...new Set(photos.map(m=>m.category))],'所有照片',filters.category)}</select><span class="small muted">♡ 加入 ${artist(artistId).name} 的个人精选</span></div><div id="detail-gallery">${mediaGrid(photos.filter(m=>!filters.category||m.category===filters.category))}</div></section></div><div class="stack"><section class="panel"><h2>客户小记</h2><p class="summary">${clientPreferences(client(b.clientId),state.memories).map(esc).join('<br>')}</p>${role==='admin'?`<p class="opportunity">${esc(client(b.clientId).opportunity)}</p>${link('clients',b.clientId,'查看完整客户档案')}`:'<div class="restriction">当前仅显示服务所需信息。客户联系方式与内部档案由管理员管理。</div>'}</section><section class="panel"><h2>场次时间线</h2><div class="timeline"><p>场次建立<small>${date(b.date)} · 示例记录</small></p><p>团队与场地已关联<small>${b.artistIds.map(x=>artist(x).name).join(' / ')}</small></p><p>${b.status==='Completed'?'工作已完成':'服务准备中'}<small>${statusName[b.status]}</small></p><p>工作记忆已收录<small>${ns.length} 条记录 · ${photos.length} 张作品照片</small></p></div></section></div></div>`}
function restricted(){return '<div class="restriction">当前视角无法查看这份档案。请通过左侧导航查看自己的场次与作品。</div>'}
function directory(type){if(type==='clients'&&role==='artist')return head(type,'')+restricted();const arr=type==='clients'?clients:type==='artists'?role==='admin'?artists:[artist(artistId)]:type==='venues'?venues:partners;return head(type,{clients:'记住客户，也记住每一次相遇。',artists:'每个人的工作，都在这里慢慢积累。',venues:'同一个地方，留下不同的故事。',partners:'把一起完成过的工作，连成关系。'}[type])+`<div class="toolbar"><input data-directory="${type}" type="search" placeholder="搜索${titles[type][1]}" aria-label="搜索${titles[type][1]}"></div><div class="grid" id="directory">${directoryCards(type,arr)}</div>`}
function directoryCards(type,arr){return arr.length?arr.map(x=>`<a class="profile-card" href="#${type}/${x.id}">${type==='artists'?(x.image?`<img src="${esc(x.image)}" alt="${esc(x.name)}">`:`<div class="member-monogram">${esc(x.name[0])}</div>`):`<div class="eyebrow">${type==='clients'?'CLIENT':type==='venues'?'VENUE':x.type}</div>`}<h3>${esc(x.name)}</h3><p>${esc(x.level||x.city||x.address||x.type)}</p>${type==='artists'?`<div class="tag-list">${x.specialties.slice(0,3).map(s=>`<span class="tag">${esc(s)}</span>`).join('')}</div>`:''}<div class="count">${countFor(type,x.id).length} ${type==='partners'?'次共同合作':'场工作记录'} <span style="float:right">查看档案</span></div></a>`).join(''):'<div class="empty">没有找到匹配的档案。</div>'}
function profile(type,id){if(type==='clients'&&role==='artist'||type==='artists'&&role==='artist'&&id!==artistId)return restricted();const arr={clients,artists,venues,partners}[type],x=get(arr,id);if(!x)return restricted();const list=countFor(type,id).sort((a,b)=>b.date.localeCompare(a.date));const photos=visibleMedia().filter(m=>list.some(b=>b.id===m.bookingId));let info='';if(type==='clients')info=`<section class="panel"><h2>客户信息</h2><dl class="info-grid">${[['城市',x.city],['电话',x.phone],['邮箱',x.email],['微信',x.wechat],['Instagram',x.instagram],['生日',x.birthday],['婚礼日期',x.weddingDate],['来源',x.referral]].map(([k,v])=>`<div><dt>${k}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl></section><section class="panel"><h2>值得记住的事</h2><p class="summary">${clientPreferences(x,state.memories).map(esc).join('<br>')}</p><p class="opportunity">${esc(x.opportunity)}</p><details><summary>查看所有工作记录</summary>${[...notes,...state.notes].filter(n=>list.some(b=>b.id===n.entityId)).map(n=>`<div class="raw">${esc(n.rawText)}</div>`).join('')}</details></section>`;
if(type==='artists')info=`<section class="panel"><h2>关于 ${esc(x.name)}</h2><p class="summary">${esc(x.bio)}</p><div class="tag-list">${x.specialties.map(s=>`<span class="tag">${esc(s)}</span>`).join('')}</div><div class="subline employee-status">${x.accountStatus==='pilot'?'试用账号准备中':'正式员工档案 · 登录待邀请'}</div><div class="divider"></div>${Object.keys(serviceName).map(s=>`<div class="entity-row"><span class="label">${serviceName[s]}</span><span>${list.filter(b=>b.service===s).length} 场</span></div>`).join('')}</section>`;
if(type==='venues'||type==='partners')info=`<section class="panel"><h2>${type==='venues'?'场地信息':'合作方信息'}</h2>${x.address?`<p class="small">${esc(x.address)}</p>`:''}${x.website?`<a class="link small" href="${esc(x.website)}" target="_blank" rel="noopener">官方网站</a>`:''}${role==='admin'?`<div class="divider"></div><h3>内部备注</h3><p class="summary">${esc(x.note)}</p>`:''}<div class="divider"></div><h3>一起工作过的化妆师</h3><div class="tag-list">${[...new Set(list.flatMap(b=>b.artistIds))].map(a=>role==='admin'||a===artistId?link('artists',a,artist(a).name):esc(artist(a).name)).join(' · ')}</div><div class="divider"></div><h3>${type==='venues'?'常合作的团队':'合作过的场地'}</h3><div class="tag-list">${type==='venues'?[...new Set(list.flatMap(b=>b.partnerIds))].map(p=>link('partners',p,partner(p).name)).join(' · '):[...new Set(list.map(b=>b.venueId))].map(v=>link('venues',v,venue(v).name)).join(' · ')}</div></section>`;
const personal=type==='artists'?portfolioMedia.filter(m=>m.artistIds.includes(id)):[];
return `<a class="back" href="#${type}">‹ 返回${titles[type][1]}</a><div class="profile-title">${type==='artists'?(x.image?`<img src="${esc(x.image)}" alt="${esc(x.name)}">`:`<div class="monogram">${esc(x.name[0])}</div>`):`<div class="monogram">${esc(x.name[0])}</div>`}<div><div class="eyebrow">${type.slice(0,-1).toUpperCase()} PROFILE</div><h1>${esc(x.name)}</h1><p>${esc(x.level||x.address||x.type||x.city)}</p></div></div>${stats([[list.length,type==='partners'?'共同合作次数':'已收录场次'],[type==='clients'&&role==='admin'?money(list.reduce((a,b)=>a+b.price,0)):photos.length,type==='clients'&&role==='admin'?'累计消费 · CAD':'归档作品'],[list.length?date(list.at(-1).date):'—','首次收录'],[list.length?date(list[0].date):'—','最近一场']])}<div class="two-col"><div class="stack"><section class="panel"><h2>历史场次</h2>${bookingTable(list)}</section>${type==='artists'&&x.bookingEligible!==false?`<section class="panel"><div class="section-head"><h2>官网精选作品</h2><span>${personal.length} 张作品</span></div><p class="small muted">直接同步自每位成员在 SCULP Studio 官网的个人 Portfolio；其他官网作品归入 Miranda。店内装修与空间照片不收录。</p>${mediaGrid(personal,false,true)}</section>`:''}<section class="panel"><h2>${type==='artists'?'历史场次作品':'关联照片'}</h2>${mediaGrid(photos.slice(0,18))}${photos.length>18?'<p class="small muted" style="margin-top:15px">此处展示最近 18 张，完整照片可在对应场次中查看。</p>':''}</section></div><div class="stack">${info}<section class="panel"><h2>记录说明</h2><p class="small muted">这里的客户、合作次数与订单都是产品演示样本。官网精选使用 SCULP Studio 公开作品；虚构订单关联仅用于演示。</p></section></div></div>`}
function mediaPage(){const members=artists.filter(a=>a.bookingEligible!==false),works=filteredPortfolioMedia();return head('media','官网作品按每位化妆师归档；各自 Portfolio 归本人，其余作品归 Miranda。')+`<div class="toolbar"><select aria-label="图库化妆师" data-media-filter="artist">${selectOptions(role==='admin'?members:[artist(artistId)],'全部化妆师',filters.artist)}</select><button data-action="media-all">查看全部官网作品</button><span class="small muted">${works.length} 张 · 已排除店内装修与空间照片</span></div><div id="media-results">${mediaGrid(works,false,true)}</div>`}
let onlyPortfolio=false;
function filteredMedia(){return visibleMedia().filter(m=>(!filters.artist||m.artistIds.includes(filters.artist))&&(!filters.category||m.category===filters.category)&&(!onlyPortfolio||state.selections.some(s=>s.mediaId===m.id&&s.artistId===artistId)))}
function filteredPortfolioMedia(){const order=new Map(artists.map((a,i)=>[a.id,i])),allowed=role==='admin'?portfolioMedia:portfolioMedia.filter(m=>m.artistIds.includes(artistId));return allowed.filter(m=>!filters.artist||m.artistIds.includes(filters.artist)).sort((a,b)=>order.get(a.artistIds[0])-order.get(b.artistIds[0]))}
function settings(){if(role==='artist')return head('settings','你的 Sculpy 账号与个人工作空间。')+`<section class="panel"><div class="setting-row"><div><h3>当前员工</h3><p>只查看自己参与的场次、服务信息和个人作品。</p></div><span class="pill">${esc(artist(artistId).name)}</span></div><div class="setting-row"><div><h3>数据权限</h3><p>客户联系方式、全局金额和其他员工后台数据不会显示。</p></div><span class="pill">EMPLOYEE</span></div></section>`;if(!isTechnical())return head('settings','Miranda 的全局业务管理空间。')+`<section class="panel"><div class="setting-row"><div><h3>全局业务权限</h3><p>可以查看全部客户、订单金额、团队、作品、合作方与经营概览。</p></div><span class="pill">OWNER</span></div><div class="setting-row"><div><h3>Sculpy 管理</h3><p>可以查看并确认团队记录、客户偏好与后续机会。</p></div><span class="pill">FULL BUSINESS</span></div><div class="setting-row"><div><h3>技术后台</h3><p>接口状态、数据库结构、审计与系统配置由 Jz 管理，此处不显示。</p></div><span class="pill">JZ MANAGED</span></div></section>`;return head('settings','Jz 的系统、数据与运营后台。')+`<section class="panel technical-panel"><div class="setting-row"><div><h3>当前权限</h3><p>完整业务数据、系统配置、数据质量、AI 状态与审计信息。</p></div><span class="pill">SYSTEM ADMIN</span></div><div class="setting-row"><div><h3>运行环境</h3><p>Demo 与 Production 已分离配置；当前页面不会写入正式数据库。</p></div><span class="pill">${config.environment.toUpperCase()}</span></div><div class="setting-row"><div><h3>Sculpy AI 接口</h3><p>语音转写、信息整理与数据库搜索使用统一接口，可在 Mock / OpenAI 间切换。</p></div><span class="pill">${config.aiMode.toUpperCase()}</span></div><div class="setting-row"><div><h3>成员与权限</h3><p>9 位成员；只有 Jz 与 Miranda 拥有全局业务权限，技术和审计权限只属于 Jz。</p></div><span class="pill">2 GLOBAL / 1 TECH</span></div><div class="setting-row"><div><h3>权限与数据库</h3><p>Supabase 表结构、行级权限与团队种子数据已完成；接入正式项目密钥后启用云端登录与同步。</p></div><span class="pill">SCHEMA READY</span></div><div class="setting-row"><div><h3>重新开始发布会演示</h3><p>清除当前浏览器新增的记录与精选调整，恢复初始示例。</p></div><button data-action="reset">恢复示例数据</button></div></section>`}
const tourSteps=[{route:'bookings',title:'1 / 8 · 一切从场次开始',text:'先看到什么时候、谁负责、在哪里。'}, {route:'bookings/b0',title:'2 / 8 · 打开一场婚礼',text:'客户、团队、场地、合作方、记录与照片都在一起。'}, {route:'clients/c0',title:'3 / 8 · 记住客户',text:'她以前做过什么，喜欢什么，有哪些值得记住的事。'}, {route:'venues/graydon',title:'4 / 8 · 记住场地',text:'我们去过多少次，与哪些人一起工作过。'}, {route:'partners/mango',title:'5 / 8 · 记住合作',text:'摄影师与 Planner 不再只是聊天里的名字。'}, {route:'artists/michelle',title:'6 / 8 · 记住每个人的积累',text:'每一场经历、每一张作品，都有自己的位置。'}, {route:'media',title:'7 / 8 · 找回作品',text:'按分类和化妆师查看，再挑出个人精选。'}, {route:'sculpy/b0',title:'8 / 8 · 告诉 Sculpy',text:'直接说出工作细节，确认后把记录放进这一场。'}];
function render(){chatPanel.detach();sculpyPage.dispose();const [type='bookings',id]=location.hash.slice(1).split('/'),key=titles[type]?type:'bookings';document.body.classList.remove('menu-open');$('#nav').innerHTML=navItems.filter(k=>role==='admin'||k!=='clients').map(k=>`<a href="#${k}" class="${key===k?'active':''}">${k==='sculpy'?'<span class="sculpy-nav-avatar" aria-hidden="true"><img src="assets/sculpy.webp" alt=""></span>':`<svg viewBox="0 0 24 24" aria-hidden="true">${iconPaths[navItems.indexOf(k)]}</svg>`}${titles[k][1]}</a>`).join('');$('#breadcrumb').textContent='工作室 / '+titles[key][1];$('#artistIdentity').hidden=role!=='artist';$('#identity').textContent=role==='admin'?(adminPersona==='jz'?'J':'M'):artist(artistId).name[0];let html='';if(key==='bookings')html=id?bookingDetail(id):bookingsPage();else if(['clients','artists','venues','partners'].includes(key))html=id?profile(key,id):directory(key);else if(key==='media')html=mediaPage();else if(key==='insights')html=insights();else if(key==='sculpy')html='<section id="sculpy-chat-root" aria-label="Sculpy 连续聊天"></section>';else html=settings();if(tour){const step=tourSteps[tour-1];html=`<div class="tour-banner"><div><p>${step.title}</p><small>${step.text}</small></div><div class="actions"><button data-action="tour-prev" ${tour===1?'disabled':''}>上一步</button><button class="primary" data-action="tour-next">${tour===8?'完成演示':'下一步'}</button><button data-action="tour-end">退出</button></div></div>`+html}$('#main').classList.toggle('sculpy-reveal',key==='sculpy');$('#main').innerHTML=html;$('#main').dataset.route=location.hash;document.title=`${config.appName} · ${titles[key][1]}`;memoryPanel.sync();chatPanel.sync();document.body.classList.toggle('sculpy-chat-page',key==='sculpy');if(key==='sculpy')chatPanel.mount($('#sculpy-chat-root'));}
const insights=createInsights({getContext,available,visibleMedia,isTechnical,head,stats,esc,link,money,artists,clients,venues,partners,bookings,notes,media,bookingArtists,artist,serviceName,config});
const serviceRevenueChart=createRevenueChart({available,serviceName,config,money,date,esc});
const sculpyPage=createSculpyPage({getContext,available,isGlobal,head,esc,date,serviceName,config,client,artists,partners,bookings,notes,get,$,toast,persist,serviceRevenueChart});
const memoryRepository=config.environment==='demo'?createDemoMemoryRepository({getState:()=>state,setState:next=>{state=next}}):createCloudMemoryRepository({supabase:null});
const memoryPanel=createMemoryPanel({data:{bookings,clients,artists,venues,partners},getContext,repository:memoryRepository,onSaved:()=>{hydrateDemoEntities();render()},esc,config});
const chatCatalog=()=>{const context=getContext(),list=available(),catalog=searchCatalog({bookings:list,artists,partners,notes:[...notes,...state.notes],client,serviceName,context});
 for(const batch of state.memories||[])for(const item of batch.items||[])if(item.entityType==='booking'&&list.some(b=>b.id===item.entityId)&&(context.role==='admin'||batch.createdBy===context.artistId||(item.status==='confirmed'&&!['task','change'].includes(item.kind))))catalog.notes.push({entityId:item.entityId,aiSummary:item.text,status:item.status,kind:item.kind});return catalog;};
const chatPanel=createChatPanel({renderSupplement:turn=>turn.chartKey==='service-revenue'&&isGlobal()?serviceRevenueChart():'',adapter:demoChatAdapter({resolveLocal:message=>wantsRevenueChart(message)?{answer:isGlobal()?'这是演示订单按已配置统计周期计算的服务收入占比。':'收入与全局经营数据仅对 Jz 和 Miranda 开放。',chartKey:isGlobal()?'service-revenue':null,references:[],proposals:[],sourceIds:[]}:null,getIdentity:()=>role==='admin'?adminPersona:artistId,getCatalog:chatCatalog,getContext,saveBatch:batch=>memoryRepository.save(batch)}),getScope:()=>{const [type,id]=location.hash.slice(1).split('/'),b=['bookings','sculpy'].includes(type)&&available().find(b=>b.id===id);return b?{id:b.id,label:client(b.clientId).name+' · '+b.date}:{id:'global',label:'全局工作助手'};}});
document.addEventListener('input',e=>sculpyPage.handleInput(e.target));
window.addEventListener('pagehide',()=>sculpyPage.dispose());
$('#artistIdentity').innerHTML=bookingArtists.map(a=>`<option value="${a.id}" ${a.id===artistId?'selected':''}>${a.name}</option>`).join('');
$('#role').addEventListener('change',e=>{role=e.target.value==='artist'?'artist':'admin';if(role==='admin')adminPersona=e.target.value==='miranda'?'miranda':'jz';tour=0;sculpyPage.dispose();filters={q:'',artist:'',service:'',status:'',date:'',venue:'',category:''};location.hash=role==='artist'?'artists/'+artistId:'bookings';render()});
$('#artistIdentity').addEventListener('change',e=>{artistId=e.target.value;sculpyPage.dispose();if(role==='artist')location.hash='artists/'+artistId;render()});
$('#menu').addEventListener('click',()=>document.body.classList.toggle('menu-open'));
window.addEventListener('hashchange',()=>{filters.category='';sculpyPage.dispose();render();window.scrollTo(0,0)});
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.body.classList.remove('menu-open')});
document.addEventListener('input',e=>{if(e.target.dataset.filter==='q'){filters.q=e.target.value;$('#booking-results').innerHTML=(view==='list'?bookingTable(filtered()):calendar(filtered()))+`<div class="results">${filtered().length} 场 · 所有记录均为示例</div>`}if(e.target.dataset.directory){const type=e.target.dataset.directory,arr={clients,artists,venues,partners}[type].filter(x=>(type!=='artists'||role==='admin'||x.id===artistId)&&x.name.toLowerCase().includes(e.target.value.toLowerCase()));$('#directory').innerHTML=directoryCards(type,arr)}});
document.addEventListener('change',e=>{const filter=e.target.dataset.filter;if(filter){filters[filter]=e.target.value;$('#booking-results').innerHTML=(view==='list'?bookingTable(filtered()):calendar(filtered()))+`<div class="results">${filtered().length} 场 · 所有记录均为示例</div>`}if(e.target.dataset.gallery){filters.category=e.target.value;$('#detail-gallery').innerHTML=mediaGrid(media.filter(m=>m.bookingId===e.target.dataset.gallery&&(!filters.category||m.category===filters.category)))}if(e.target.dataset.mediaFilter){filters[e.target.dataset.mediaFilter]=e.target.value;const works=filteredPortfolioMedia();$('#media-results').innerHTML=mediaGrid(works,false,true);const count=e.target.closest('.toolbar')?.querySelector('.small.muted');if(count)count.textContent=`${works.length} 张 · 已排除店内装修与空间照片`}});
document.addEventListener('click',e=>{const button=e.target.closest('button[data-photo][data-official="true"]');if(!button)return;const item=get(portfolioMedia,button.dataset.photo);if(!item)return;e.stopImmediatePropagation();$('#lightbox img').src=item.fileUrl;$('#lightbox p').textContent=artist(item.artistIds[0]).name+' · SCULP Studio 官网精选作品';$('#lightbox').showModal()},true);
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view){view=b.dataset.view;render()}if(b.dataset.month){const [y,m]=month.split('-').map(Number),d=new Date(y,m-1+Number(b.dataset.month),1);month=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');render()}if(b.dataset.photo){const m=get(visibleMedia(),b.dataset.photo);if(!m)return;$('#lightbox img').src=m.fileUrl;$('#lightbox p').textContent=m.category+' · SCULP 展示作品 / 虚构场次关联仅作演示';$('#lightbox').showModal()}if(b.classList.contains('close'))$('#lightbox').close();if(b.dataset.select){const m=get(visibleMedia(),b.dataset.select);if(!m||!m.artistIds.includes(artistId)){toast('请在右上角切换为参与这场的化妆师，再整理她的精选。');return}const i=state.selections.findIndex(s=>s.mediaId===m.id&&s.artistId===artistId);if(i<0)state.selections.push({mediaId:m.id,artistId,collection:'personal',selectedAt:new Date().toISOString()});else state.selections.splice(i,1);persist();render();toast(i<0?'已加入 '+artist(artistId).name+' 的个人精选':'已从个人精选移除')}if(b.dataset.order){const own=state.selections.filter(s=>s.artistId===artistId),i=own.findIndex(s=>s.mediaId===b.dataset.order),j=i+Number(b.dataset.direction);if(j<0||j>=own.length)return;const a=state.selections.indexOf(own[i]),c=state.selections.indexOf(own[j]);[state.selections[a],state.selections[c]]=[state.selections[c],state.selections[a]];persist();render()}
const action=b.dataset.action;if(action==='clear'){filters={q:'',artist:'',service:'',status:'',date:'',venue:'',category:''};render()}if(action==='portfolio'){onlyPortfolio=true;$('#media-results').innerHTML=mediaGrid(filteredMedia())}if(action==='media-all'){onlyPortfolio=false;filters.artist='';filters.category='';render()}if(action==='tour'){role='admin';$('#role').value='admin';tour=1;location.hash=tourSteps[0].route;render()}if(action==='tour-prev'||action==='tour-next'){tour+=action==='tour-prev'?-1:1;if(tour>8){tour=0;toast('Sculpy 开始有记忆了。');render()}else{location.hash=tourSteps[tour-1].route;render();window.scrollTo(0,0)}}if(action==='tour-end'){tour=0;render()}sculpyPage.handleAction(b);if(action==='reset'){if(confirm('恢复初始示例？当前浏览器新增的工作记录与精选调整会被清除。')){resetState();state=loadState();for(let i=clients.length-1;i>=0;i--)if(clients[i].id.startsWith('demo-'))clients.splice(i,1);for(let i=bookings.length-1;i>=0;i--)if(bookings[i].id.startsWith('demo-'))bookings.splice(i,1);tour=0;render();toast('已恢复示例数据。')}}});
$('#lightbox').addEventListener('click',e=>{if(e.target===$('#lightbox'))$('#lightbox').close()});
render();
