-- Sculpy V2 production core.
-- Additive migration: keeps the V1 demo-compatible tables while introducing
-- proper commercial records, explicit admin boundaries and auditable AI use.

create type public.invoice_status as enum ('draft','issued','partially_paid','paid','void','overdue');
create type public.payment_status as enum ('pending','succeeded','failed','refunded','partially_refunded');
create type public.payment_method as enum ('cash','etransfer','credit_card','debit_card','bank_transfer','other');
create type public.ai_run_status as enum ('queued','running','completed','failed','cancelled');
create type public.ai_message_role as enum ('user','assistant','tool');

-- Identity and access -------------------------------------------------------

alter table public.profiles
 add column if not exists email text,
 add column if not exists timezone text not null default 'America/Toronto',
 add column if not exists last_seen_at timestamptz;

alter table public.media add column if not exists updated_at timestamptz not null default now();
alter table public.portfolio_items add column if not exists updated_at timestamptz not null default now();
alter table public.reminders add column if not exists updated_at timestamptz not null default now();
alter table public.ai_drafts add column if not exists updated_at timestamptz not null default now();
alter table public.services add column if not exists updated_at timestamptz not null default now();

-- Only Miranda (owner) and Jz (operations) are global business viewers.
-- Technical/system data is intentionally limited to Jz's operations role.
create or replace function public.is_business_admin() returns boolean
language sql stable security definer set search_path=public
as $$ select coalesce(public.current_app_role() in ('owner','operations'),false) $$;

create or replace function public.is_staff_manager() returns boolean
language sql stable security definer set search_path=public
as $$ select public.is_business_admin() $$;

create or replace function public.is_system_admin() returns boolean
language sql stable security definer set search_path=public
as $$ select coalesce(public.current_app_role()='operations',false) $$;

-- Customer and event records ----------------------------------------------

alter table public.clients
 add column if not exists preferred_name text,
 add column if not exists preferred_language text,
 add column if not exists timezone text not null default 'America/Toronto',
 add column if not exists tags text[] not null default '{}';

alter table public.bookings
 add column if not exists booking_number bigint generated by default as identity,
 add column if not exists title text,
 add column if not exists timezone text not null default 'America/Toronto',
 add column if not exists guest_count integer check (guest_count is null or guest_count >= 0),
 add column if not exists preparation_address text,
 add column if not exists currency char(3) not null default 'CAD',
 add column if not exists confirmed_at timestamptz,
 add column if not exists completed_at timestamptz,
 add column if not exists cancelled_at timestamptz,
 add constraint bookings_time_order check (ends_at is null or ends_at > starts_at),
 add constraint bookings_nonnegative_totals check (
   coalesce(price_cad,0) >= 0 and coalesce(deposit_cad,0) >= 0 and coalesce(balance_cad,0) >= 0
 );

create unique index if not exists bookings_booking_number_idx on public.bookings(booking_number);
create index if not exists bookings_active_status_date_idx
 on public.bookings(status, starts_at) where deleted_at is null;

-- A booking can contain several services. Prices live on immutable line
-- items so historical reporting does not change when the service menu does.
create table public.booking_services (
 id uuid primary key default gen_random_uuid(),
 booking_id uuid not null references public.bookings(id) on delete cascade,
 service_id uuid references public.services(id) on delete restrict,
 description text not null,
 quantity numeric(8,2) not null default 1 check (quantity > 0),
 unit_price numeric(12,2) not null default 0 check (unit_price >= 0),
 discount_amount numeric(12,2) not null default 0 check (discount_amount >= 0),
 tax_amount numeric(12,2) not null default 0 check (tax_amount >= 0),
 line_total numeric(12,2) generated always as (
   greatest((quantity * unit_price) - discount_amount + tax_amount, 0)
 ) stored,
 position integer not null default 0,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);

create index booking_services_booking_id_idx on public.booking_services(booking_id);

alter table public.booking_artists
 add column if not exists call_time timestamptz,
 add column if not exists finish_time timestamptz;

-- Compensation is separate from the shared assignment row so one artist
-- cannot infer another artist's pay while viewing the same booking.
create table public.artist_compensations (
 id uuid primary key default gen_random_uuid(),
 booking_id uuid not null,
 artist_id uuid not null,
 amount numeric(12,2) not null check (amount >= 0),
 currency char(3) not null default 'CAD',
 status text not null default 'pending' check (status in ('pending','approved','paid','void')),
 paid_at timestamptz,
 internal_notes text,
 created_by uuid references public.profiles(id),
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 foreign key (booking_id,artist_id)
   references public.booking_artists(booking_id,artist_id) on delete cascade,
 unique (booking_id,artist_id)
);

-- Commercial records -------------------------------------------------------

create table public.invoices (
 id uuid primary key default gen_random_uuid(),
 invoice_number bigint generated by default as identity unique,
 booking_id uuid not null references public.bookings(id) on delete restrict,
 status public.invoice_status not null default 'draft',
 currency char(3) not null default 'CAD',
 subtotal numeric(12,2) not null default 0 check (subtotal >= 0),
 discount_amount numeric(12,2) not null default 0 check (discount_amount >= 0),
 tax_amount numeric(12,2) not null default 0 check (tax_amount >= 0),
 total_amount numeric(12,2) generated always as (
   greatest(subtotal - discount_amount + tax_amount, 0)
 ) stored,
 issued_at timestamptz,
 due_at timestamptz,
 notes text,
 created_by uuid references public.profiles(id),
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 deleted_at timestamptz
);

create table public.payments (
 id uuid primary key default gen_random_uuid(),
 invoice_id uuid not null references public.invoices(id) on delete restrict,
 amount numeric(12,2) not null check (amount > 0),
 currency char(3) not null default 'CAD',
 method public.payment_method not null,
 status public.payment_status not null default 'pending',
 paid_at timestamptz,
 external_reference text,
 internal_notes text,
 created_by uuid references public.profiles(id),
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);

create index invoices_booking_id_idx on public.invoices(booking_id) where deleted_at is null;
create index payments_invoice_id_idx on public.payments(invoice_id);
create index payments_paid_at_idx on public.payments(paid_at) where status='succeeded';
create index artist_compensations_artist_id_idx on public.artist_compensations(artist_id);

-- Consent is versioned rather than overwritten. This protects portfolio and
-- marketing decisions when a customer later changes their permission.
create table public.client_consents (
 id uuid primary key default gen_random_uuid(),
 client_id uuid not null references public.clients(id) on delete cascade,
 booking_id uuid references public.bookings(id) on delete set null,
 consent_type text not null check (consent_type in ('portfolio','social_media','marketing_contact','ai_processing')),
 granted boolean not null,
 source text not null default 'staff_recorded',
 evidence_storage_path text,
 captured_by uuid references public.profiles(id),
 captured_at timestamptz not null default now(),
 revoked_at timestamptz,
 notes text
);

create index client_consents_client_type_idx
 on public.client_consents(client_id, consent_type, captured_at desc);

-- Sculpy assistant ---------------------------------------------------------

create table public.ai_threads (
 id uuid primary key default gen_random_uuid(),
 created_by uuid not null references public.profiles(id),
 title text,
 booking_id uuid references public.bookings(id) on delete set null,
 client_id uuid references public.clients(id) on delete set null,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 archived_at timestamptz
);

create table public.ai_messages (
 id uuid primary key default gen_random_uuid(),
 thread_id uuid not null references public.ai_threads(id) on delete cascade,
 role public.ai_message_role not null,
 content text not null,
 citations jsonb not null default '[]',
 visible_to_user boolean not null default true,
 created_at timestamptz not null default now()
);

create table public.ai_runs (
 id uuid primary key default gen_random_uuid(),
 thread_id uuid references public.ai_threads(id) on delete set null,
 requested_by uuid not null references public.profiles(id),
 purpose text not null check (purpose in ('transcription','extraction','search','report','decision_support')),
 model_name text,
 status public.ai_run_status not null default 'queued',
 query_text text,
 input_record_ids jsonb not null default '[]',
 output_record_ids jsonb not null default '[]',
 prompt_tokens integer check (prompt_tokens is null or prompt_tokens >= 0),
 completion_tokens integer check (completion_tokens is null or completion_tokens >= 0),
 estimated_cost_usd numeric(12,6) check (estimated_cost_usd is null or estimated_cost_usd >= 0),
 error_code text,
 started_at timestamptz,
 completed_at timestamptz,
 created_at timestamptz not null default now()
);

create index ai_threads_created_by_idx on public.ai_threads(created_by, updated_at desc);
create index ai_messages_thread_id_idx on public.ai_messages(thread_id, created_at);
create index ai_runs_requested_by_idx on public.ai_runs(requested_by, created_at desc);

-- Trusted reporting views. Sculpy reads these totals instead of inventing
-- arithmetic in a language-model response.
create or replace view public.booking_financials
with (security_invoker=true) as
select
 b.id as booking_id,
 b.client_id,
 b.starts_at,
 b.status,
 b.currency,
 coalesce(sum(bs.line_total), b.price_cad, 0)::numeric(12,2) as booked_total,
 coalesce((
   select sum(p.amount)
   from public.invoices i
   join public.payments p on p.invoice_id=i.id
   where i.booking_id=b.id and i.deleted_at is null and p.status='succeeded'
 ),0)::numeric(12,2) as paid_total
from public.bookings b
left join public.booking_services bs on bs.booking_id=b.id
where b.deleted_at is null
group by b.id;

create or replace view public.service_revenue_monthly
with (security_invoker=true) as
select
 date_trunc('month', coalesce(p.paid_at, p.created_at)) as revenue_month,
 bs.service_id,
 s.code as service_code,
 s.name as service_name,
 sum(
   p.amount * case when inv.total_amount > 0 then bs.line_total / inv.total_amount else 0 end
 )::numeric(12,2) as recognized_revenue
from public.payments p
join public.invoices inv on inv.id=p.invoice_id and inv.deleted_at is null
join public.booking_services bs on bs.booking_id=inv.booking_id
left join public.services s on s.id=bs.service_id
where p.status='succeeded'
group by 1,2,3,4;

-- Timestamp and audit helpers ---------------------------------------------

create or replace function public.set_updated_at() returns trigger
language plpgsql set search_path=public
as $$ begin new.updated_at=now(); return new; end $$;

create or replace function public.write_audit_event() returns trigger
language plpgsql security definer set search_path=public
as $$
declare record_json jsonb;
begin
 record_json=case when TG_OP='DELETE' then to_jsonb(old) else to_jsonb(new) end;
 insert into public.audit_events(actor_id,entity_type,entity_id,action,before_value,after_value)
 values (
   auth.uid(), TG_TABLE_NAME,
   coalesce(record_json->>'id',record_json->>'booking_id',record_json->>'client_id')::uuid,
   lower(TG_OP),
   case when TG_OP in ('UPDATE','DELETE') then to_jsonb(old) else null end,
   case when TG_OP in ('INSERT','UPDATE') then to_jsonb(new) else null end
 );
 if TG_OP='DELETE' then return old; end if;
 return new;
end $$;

do $$
declare table_name text;
begin
 foreach table_name in array array[
   'profiles','artists','clients','venues','partners','bookings','work_logs',
   'client_private','services','media','portfolio_items','reminders','ai_drafts','booking_services',
   'artist_compensations','invoices','payments','ai_threads'
 ] loop
   execute format('drop trigger if exists set_%I_updated_at on public.%I',table_name,table_name);
   execute format(
     'create trigger set_%I_updated_at before update on public.%I for each row execute function public.set_updated_at()',
     table_name, table_name
   );
 end loop;
end $$;

do $$
declare table_name text;
begin
 foreach table_name in array array[
   'clients','client_private','bookings','booking_services','booking_artists',
   'artist_compensations','invoices','payments','client_consents','work_logs','media','portfolio_items'
 ] loop
   execute format('drop trigger if exists audit_%I on public.%I',table_name,table_name);
   execute format(
     'create trigger audit_%I after insert or update or delete on public.%I for each row execute function public.write_audit_event()',
     table_name, table_name
   );
 end loop;
end $$;

-- Row-level security -------------------------------------------------------

alter table public.booking_services enable row level security;
alter table public.artist_compensations enable row level security;
alter table public.invoices enable row level security;
alter table public.payments enable row level security;
alter table public.client_consents enable row level security;
alter table public.ai_threads enable row level security;
alter table public.ai_messages enable row level security;
alter table public.ai_runs enable row level security;

create policy booking_services_read_related on public.booking_services for select
 using (public.is_business_admin() or public.is_assigned_to_booking(booking_id));
create policy booking_services_manage_admin on public.booking_services for all
 using (public.is_business_admin()) with check (public.is_business_admin());

create policy artist_compensations_admin_only on public.artist_compensations for all
 using (public.is_business_admin()) with check (public.is_business_admin());

create policy invoices_admin_only on public.invoices for all
 using (public.is_business_admin()) with check (public.is_business_admin());
create policy payments_admin_only on public.payments for all
 using (public.is_business_admin()) with check (public.is_business_admin());
create policy consents_admin_only on public.client_consents for all
 using (public.is_business_admin()) with check (public.is_business_admin());

create policy ai_threads_read_own_or_admin on public.ai_threads for select
 using (created_by=auth.uid() or public.is_business_admin());
create policy ai_threads_create_own on public.ai_threads for insert
 with check (created_by=auth.uid());
create policy ai_threads_update_own_or_admin on public.ai_threads for update
 using (created_by=auth.uid() or public.is_business_admin())
 with check (created_by=auth.uid() or public.is_business_admin());

create policy ai_messages_read_thread on public.ai_messages for select
 using (exists(
   select 1 from public.ai_threads t
   where t.id=thread_id and (t.created_by=auth.uid() or public.is_business_admin())
 ));
create policy ai_messages_create_thread on public.ai_messages for insert
 with check (exists(
   select 1 from public.ai_threads t
   where t.id=thread_id and t.created_by=auth.uid()
 ) and role='user'
 );

-- The Edge Function uses its service role for run creation and completion.
-- End users can read their own run metadata but cannot forge usage/cost logs.
drop policy if exists ai_runs_create_own on public.ai_runs;

create policy ai_runs_read_own_or_system on public.ai_runs for select
 using (requested_by=auth.uid() or public.is_system_admin());
create policy ai_runs_update_system on public.ai_runs for update
 using (public.is_system_admin()) with check (public.is_system_admin());

-- Prevent soft-deleted records from appearing through existing read policies.
drop policy if exists clients_read_related on public.clients;
create policy clients_read_related on public.clients for select using (
 deleted_at is null and (
   public.is_business_admin() or exists(
     select 1 from public.bookings b
     where b.client_id=clients.id and b.deleted_at is null and public.is_assigned_to_booking(b.id)
   )
 )
);

drop policy if exists bookings_read_assigned on public.bookings;
create policy bookings_read_assigned on public.bookings for select using (
 deleted_at is null and (public.is_business_admin() or public.is_assigned_to_booking(id))
);

drop policy if exists audit_read_system_admin on public.audit_events;
create policy audit_read_system_admin on public.audit_events for select
 using (public.is_system_admin());

comment on view public.booking_financials is 'Authoritative booking totals for UI and Sculpy tools; inherits caller RLS.';
comment on view public.service_revenue_monthly is 'Payment-derived monthly service revenue; global business viewers only through underlying RLS.';
comment on table public.ai_runs is 'Minimal AI observability: purpose, sources, outputs, token use and cost; visible to requester or Jz.';
